#!/usr/bin/env bash

OS=$(uname | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
EXE="$SCRIPT_DIR/pbench_${OS}_${ARCH}"

if [ ! -f "$EXE" ]; then
    if [ -f Makefile ]; then
      make
    else
      echo "Cannot find $EXE"
      exit 1
    fi
fi

$EXE "$@"
