FROM quay.io/centos/centos:stream8

ARG PRESTO_VERSION
ARG PRESTO_PKG=presto-server-$PRESTO_VERSION.tar.gz
ARG PRESTO_CLI_JAR=presto-cli-$PRESTO_VERSION-executable.jar

ENV PRESTO_HOME="/opt/presto-server"

COPY presto-server/target/$PRESTO_PKG .
COPY presto-cli/target/$PRESTO_CLI_JAR /opt/presto-cli

RUN dnf install -y java-11-openjdk less procps python3 \
    && ln -s $(which python3) /usr/bin/python \
    # clean cache jobs
    && mv /etc/yum/protected.d/systemd.conf /etc/yum/protected.d/systemd.conf.bak \
    && dnf clean all \
    # Download jmx prometheus exporter
    && mkdir -p /usr/lib/presto/utils \
    && curl -o /usr/lib/presto/utils/jmx_prometheus_javaagent-0.20.0.jar https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar

# Download Presto and move
RUN tar -zxf $PRESTO_PKG \
    && mv ./presto-server-$PRESTO_VERSION $PRESTO_HOME \
    && rm -rf $PRESTO_PKG \
    && chmod +x /opt/presto-cli \
    && ln -s /opt/presto-cli /usr/local/bin/ \
    #  mkdir for config
    && mkdir -p $PRESTO_HOME/etc/catalog \
    && mkdir -p /var/lib/presto/data

COPY docker/etc/config.properties.example $PRESTO_HOME/etc/config.properties
COPY docker/etc/jvm.config.example $PRESTO_HOME/etc/jvm.config
COPY docker/etc/node.properties $PRESTO_HOME/etc/node.properties
COPY docker/entrypoint.sh /opt

EXPOSE 8080

# ENTRYPOINT ["/opt/entrypoint.sh"]
