{{ template "prelude" . -}}
{{- if .generate_spark_config -}}
version: '3.8'

networks:
  presto-swarm:

services:
  coordinator:
    image: ${PRESTO_COORDINATOR_IMAGE}
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_MASTER_HOST=0.0.0.0
      {{- if eq .cluster_size "xlarge-ssd" }}
      - SPARK_LOCAL_DIRS=/opt/spark/localdir/data1,/opt/spark/localdir/data2
      {{- else if hasSuffix .cluster_size "ssd" }}
      - SPARK_LOCAL_DIRS=/opt/spark/localdir/data1
      {{- end }}
      {{- if hasPrefix .coordinator_instance_type "g" }}
      - NVIDIA_VISIBLE_DEVICES=all
      {{- end }}
    deploy:
      placement:
        constraints:
        - node.role == manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '{{ dec .vcpu_per_worker }}'
          memory: {{ .container_memory_gb }}G
        reservations:
          cpus: '{{ dec .vcpu_per_worker }}'
          memory: {{ .container_memory_gb }}G
    ports:
    - 80:8080
    - 4040:4040
    - 4041:4041
    - 6066:6066
    - 7077:7077
    - 8081:8081
    - 8989:8989
    - 15002:15002
    - 18080:18080
    entrypoint:
    - /bin/bash
    - /opt/entrypoint-spark.sh
    volumes:
    - /home/centos/presto/log/spark/events:/opt/spark/events
    - /home/centos/presto/log/spark/logs:/opt/spark/logs
    - /home/centos/presto/log/spark/work:/opt/spark/work
    {{- if hasSuffix .cluster_size "ssd" }}
    - /home/centos/presto/mnt_data/data1:/opt/spark/localdir/data1
    {{- end }}
    {{- if eq .cluster_size "xlarge-ssd" }}
    - /home/centos/presto/mnt_data/data2:/opt/spark/localdir/data2
    {{- end }}
    - /home/centos/presto/spark/hive-site.xml:/opt/spark/conf/hive-site.xml
    - /home/centos/presto/spark/log4j2.properties:/opt/spark/conf/log4j2.properties
    - /home/centos/presto/spark/metrics.properties:/opt/spark/conf/metrics.properties
    - /home/centos/presto/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    - /home/centos/presto/spark/spark-native-defaults.conf:/opt/spark/conf/spark-native-defaults.conf
    - /home/centos/presto/entrypoint-spark.sh:/opt/entrypoint-spark.sh
    - /usr/bin/telegraf:/usr/bin/telegraf
    - /etc/telegraf:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      presto-swarm:

  workers:
    image: ${PRESTO_WORKER_IMAGE}
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://coordinator:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      {{- if eq .cluster_size "xlarge-ssd" }}
      - SPARK_LOCAL_DIRS=/opt/spark/localdir/data1,/opt/spark/localdir/data2
      {{- else if hasSuffix .cluster_size "ssd" }}
      - SPARK_LOCAL_DIRS=/opt/spark/localdir/data1
      {{- end }}
      {{- if hasPrefix .worker_instance_type "g" }}
      - NVIDIA_VISIBLE_DEVICES=all
      {{- end }}
    depends_on:
    - coordinator
    deploy:
      placement:
        constraints:
        - node.role == worker
      mode: replicated
      replicas: ${NUMBER_OF_WORKERS}
      resources:
        limits:
          cpus: '{{ dec .vcpu_per_worker }}'
          memory: {{ .container_memory_gb }}G
        reservations:
          cpus: '{{ dec .vcpu_per_worker }}'
          memory: {{ .container_memory_gb }}G
    entrypoint:
    - /bin/bash
    - /opt/entrypoint-spark.sh
    volumes:
    - /home/centos/presto/log/spark/events:/opt/spark/events
    - /home/centos/presto/log/spark/logs:/opt/spark/logs
    - /home/centos/presto/log/spark/work:/opt/spark/work
    {{- if hasSuffix .cluster_size "ssd" }}
    - /home/centos/presto/mnt_data/data1:/opt/spark/localdir/data1
    {{- end }}
    {{- if eq .cluster_size "xlarge-ssd" }}
    - /home/centos/presto/mnt_data/data2:/opt/spark/localdir/data2
    {{- end }}
    - /home/centos/presto/spark/hive-site.xml:/opt/spark/conf/hive-site.xml
    - /home/centos/presto/spark/log4j2.properties:/opt/spark/conf/log4j2.properties
    - /home/centos/presto/spark/metrics.properties:/opt/spark/conf/metrics.properties
    - /home/centos/presto/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    - /home/centos/presto/spark/spark-native-defaults.conf:/opt/spark/conf/spark-native-defaults.conf
    - /home/centos/presto/entrypoint-spark.sh:/opt/entrypoint-spark.sh
    - /usr/bin/telegraf:/usr/bin/telegraf
    - /etc/telegraf:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      presto-swarm:
    cap_add:
    - PERFMON
{{- end }}
