version: '3.8'

networks:
  presto-swarm:

services:
  coordinator:
    image: ${PRESTO_COORDINATOR_IMAGE}
    deploy:
      placement:
        constraints:
        - node.role == manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '{{ dec .VCPUPerWorker }}'
          memory: {{ .ContainerMemoryGb }}G
        reservations:
          cpus: '{{ dec .VCPUPerWorker }}'
          memory: {{ .ContainerMemoryGb }}G
    ports:
    - "80:8080"
    - "9404:9404"
    entrypoint:
    - /bin/bash
    - /opt/entrypoint-java.sh
    volumes:
    - /home/centos/presto/catalog/hive-native.properties:/opt/presto-server/etc/catalog/hive.properties
    - /home/centos/presto/catalog/iceberg-native-coordinator.properties:/opt/presto-server/etc/catalog/iceberg.properties
    - /home/centos/presto/catalog/jmx.properties:/opt/presto-server/etc/catalog/jmx.properties
    - /home/centos/presto/catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
    - /home/centos/presto/catalog/tpch-standard.properties:/opt/presto-server/etc/catalog/tpch.properties
    - /home/centos/presto/coordinator/config-native.properties:/opt/presto-server/etc/config.properties
    - /home/centos/presto/coordinator/jvm.config:/opt/presto-server/etc/jvm.config
    - /home/centos/presto/coordinator/node.properties:/opt/presto-server/etc/node.properties
    - /home/centos/presto/coordinator/session-property-config.json:/opt/presto-server/etc/session-property-config.json
    - /home/centos/presto/coordinator/session-property-config.properties:/opt/presto-server/etc/session-property-config.properties
    - /home/centos/presto/event-listener.properties:/opt/presto-server/etc/event-listener.properties
    - /home/centos/presto/jmx-exporter-config.yaml:/opt/presto-server/etc/jmx-exporter-config.yaml
    - /home/centos/presto/log.properties:/opt/presto-server/etc/log.properties
    - /home/centos/presto/log4j-events.properties:/opt/presto-server/etc/log4j-events.properties
    - /home/centos/presto/entrypoint-java.sh:/opt/entrypoint-java.sh
    - /usr/bin/telegraf:/usr/bin/telegraf
    - /etc/telegraf:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/centos/presto/plugin/event-listener/:/opt/presto-server/plugin/event-listener/
    - /home/centos/presto/log/presto-server/:/var/log/presto-server/
    networks:
      presto-swarm:

  workers:
    image: ${PRESTO_WORKER_IMAGE}
    depends_on:
    - coordinator
    deploy:
      placement:
        constraints:
        - node.role == worker
      mode: replicated
      replicas: ${NUMBER_OF_WORKERS}
      resources:
        limits:
          cpus: '{{ dec .VCPUPerWorker }}'
          memory: {{ .ContainerMemoryGb }}G
        reservations:
          cpus: '{{ dec .VCPUPerWorker }}'
          memory: {{ .ContainerMemoryGb }}G
    ports:
    - "8080:8080"
    - "2024:22"
    entrypoint:
    - /bin/bash
    - /opt/entrypoint-native.sh
    volumes:
    - /home/centos/presto/catalog/hive-native.properties:/opt/presto-server/etc/catalog/hive.properties
    - /home/centos/presto/catalog/iceberg-native-worker.properties:/opt/presto-server/etc/catalog/iceberg.properties
    - /home/centos/presto/catalog/tpch-standard.properties:/opt/presto-server/etc/catalog/tpch.properties
    - /home/centos/presto/workers/config-native.properties:/opt/presto-server/etc/config.properties
    - /home/centos/presto/workers/node.properties:/opt/presto-server/etc/node.properties
    - /home/centos/presto/workers/velox.properties:/opt/presto-server/etc/velox.properties
    - /home/centos/presto/async_data_cache:/opt/presto-server/async_data_cache
    - /home/centos/presto/entrypoint-native.sh:/opt/entrypoint-native.sh
    - /usr/bin/telegraf:/usr/bin/telegraf
    - /etc/telegraf:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/centos/.ssh/authorized_keys:/root/.ssh/authorized_keys2
    - /etc/ssh:/etc/ssh
    - /home/centos/presto/log/presto-server/:/var/log/presto-server/{{ if .SpillEnabled }}
    # spilling is on
    - /home/centos/presto/spilled_data:/opt/presto-server/spilled_data{{ end }}
    networks:
      presto-swarm:
